name: p4
channels:
  - defaults
dependencies:
  - python=3.12  # or your desired python version
  - pip  # ensure pip is installed in the environment
  - pip:
      - bottleneck 
      - coloredlogs==15.0.1
      - flatbuffers==25.2.10
      - humanfriendly==10.0
      - mkl-service==2.4.0
      - mkl_fft 
      - mkl_random 
      - mpmath==1.3.0
      - numexpr 
      - numpy==2.2.3
      - onnx==1.17.0
      - pandas 
      - protobuf==6.30.0
      - py4j 
      - pyarrow 
      - pyspark 
      - python-dateutil 
      - pytz 
      - setuptools==75.8.0
      - six 
      - sympy==1.13.3
      - tzdata 
      - wheel==0.45.1
