model_name: 'lstm' # lstm, bigru, 1dcnn, hybrid
experiment_name: 'TEST' # name to save as file
arch_param:
   n_features: 10
   hidden_size: 64
   num_layers: 2
   output_size: 2
   n_classes: 1
   output_seq_len: 20
   out_channels: 64
   seq_len: 60
train:
   batch_size: 256
   num_epochs: 50
   seed: 42
   lr: 0.001
   num_workers: 2
   dropout_prop: 0.2
scheduler:
  step_size: 20
  gamma: 0.1
wandb:
  project: "P4_Gatehouse"
ddp:
  set_device: "LOCAL_RANK"
  process_group: "nccl"