MMSI: 220141000
window_size: 30
step_size: 20
data_path: "aisdk-2024-06-04_fishing_labeled.csv"
cable_coordinates_path : "./data/cable_coordinates.csv"
normalization_stats_path: "./data/train_norm_stats.json"
model_paths:
  classifier: ./models/lstm_seq_5min_clf.onnx
  forecaster: ./models/s2s_lstm_seq_5min_fc.onnx
